### ISSUE TITLE
zero-valued traitlet attributes get ignored

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#100]
```python
>>> CellConfig(strokeWidth=1).to_dict()
{'strokeWidth': 1.0}
>>> CellConfig(strokeWidth=0).to_dict()
{}
```
This should be ``{'strokeWidth': 0.0}``. From a quick glance at the code, I'm not sure where this is being lost...

**Comment by ellisonbg** [comment]
For some reason containment is failing:

`'strokeWidth' in CellConfig(strokeWidth=0)`

We do a containment test in the to_dict method of BaseObject. I think we
can change that to hasattr(self, name) instead and it will be fine. I have
no idea why it is doing that though - probably a bug in traitlets.



On Thu, May 19, 2016 at 8:31 PM, Jake Vanderplas <notifications@github.com>
wrote:

> >>> CellConfig(strokeWidth=1).to_dict()
> {'strokeWidth': 1.0}>>> CellConfig(strokeWidth=0).to_dict()
> {}
>
> This should be {'strokeWidth': 0.0}. From a quick glance at the code, I'm
> not sure where this is being lost...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/100>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Actually, it could be due to the logic in ``BaseObject.__contains__``, which includes a ``not value`` statement.

**Comment by jakevdp** [comment]
Fixed in https://github.com/ellisonbg/altair/commit/0d6e69745a73c36e42a2630699a8f99177d80896
