### ISSUE TITLE
Fix Datetime Serialization

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#108]
In https://github.com/ellisonbg/altair/pull/107/commits/976bd5f36708b2f24a9dbf3c6bb64f942c230d4e I added a quick fix for the most common case: ``datetime64[ns]``. We should add suitable string formatting for other units as well.

**Comment by ellisonbg** [comment]
Are there other dtypes used for datetimes in pandas that we need to handle?

Should we also make this fix in ipyvega as well?

**Comment by jakevdp** [comment]
Fixed in https://github.com/ellisonbg/altair/pull/119
