### ISSUE TITLE
Additional aliases

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#126]
There are a few other class names that we alias in `api.py`:

* `AxisProperties`->`Axis`
* `BinProperties`->`Bin`
* `LegendProperties`->`Legend`
* `VgFormula`->`Formula`

Two action items related to these:

* The Python code generation currently uses the unaliased names.
* We might want to autogenerate the aliased classes rather than handcoding them in `api.py`

**Comment by kanitw** [comment]
FYI, in Vega-Lite, we already renamed all of them as you suggested and no longer have `XXXProperties` (e.g., `AxisProperties` becomes `Axis`). 

Same for `Formula` (We no longer have `VgFormula`).

**Comment by jakevdp** [comment]
Thanks @kanitw – which vega-lite release will those new names appear in?

**Comment by kanitw** [comment]
Starting from [v1.0.10](https://github.com/vega/vega-lite/releases) we have this :)

**Comment by jakevdp** [comment]
Great – thanks! We're hoping to update altair to vega-lite 1.0.10 very soon.

**Comment by jakevdp** [comment]
Taken care of with the move to 1.0.10
