### ISSUE TITLE
API question: should we implement encode_x(), etc.?

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#132]
Currently we have two ways of specifying configurations, which are equivalent:
``Chart().configure(cell=CellConfig(**kwargs))`` and
``Chart().configure_cell(**kwargs)``.

On the other hand, for encodings we have
 ``Chart().encode(x=X('name', **kwds))`` or ``Chart().encode(x='name')``, where in the second shorthand there is no way to specify additional keywords.

I wonder if it wouldn't be convenient to have, by analogy with the ``configure`` methods, ``Chart().encode_x('name', **kwds)``?

On the one hand, there are situations where it would be very useful – especially for tab-completion of arguments within the function. It also creates some symmetry with the ``configure_*`` methods, and users might expect to be able to do this. On the other hand, it would add yet another way of solving the same probelm, and is not particularly convenient for the most common case of defining several encodings at once.

Thoughts?

**Comment by ellisonbg** [comment]
The issue with encode is that it accepts multiple different objects, each
with its own keywords arguments. Because of this, my thought is to keep as
is.

On Wed, Jun 15, 2016 at 10:38 PM, Jake Vanderplas <notifications@github.com>
wrote:

> Currently we have two ways of specifying configurations, which are
> equivalent:
> Chart().configure(cell=CellConfig(**kwargs)) and
> Chart().configure_cell(**kwargs).
>
> On the other hand, for encodings we have
> Chart().encode(x=X('name', **kwds)) or Chart().encode(x='name'), where in
> the second shorthand there is no way to specify additional keywords.
>
> I wonder if it wouldn't be convenient to have, by analogy with the
> configure methods, Chart().encode_x('name', **kwds)?
>
> On the one hand, there are situations where it would be very useful –
> especially for tab-completion of arguments within the function. It also
> creates some symmetry with the configure_* methods, and users might
> expect to be able to do this. On the other hand, it would add yet another
> way of solving the same probelm, and is not particularly convenient for the
> most common case of defining several encodings at once.
>
> Thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/132>, or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0BSPti6H2jsDMb-YSQv6k3OkH_g-ks5qMOFMgaJpZM4I3CrR>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Sounds good
