### ISSUE TITLE
rc1 comment.

### ISSUE THREAD

**Issue by Carreau** [ellisonbg/altair#140]
As per @ellisonbg testing RC1 and commenting, apologies for shortness, I'll assume you want efficiencies and quick review for SciPy.

It looks really great ! Here are what goes through my mind as explore. Sorry if it's all over the place.

```
Altair requires the following dependencies:

numpy
pandas
py.test
```

If this is true, it should be in setup.py `install_requires`, or don't say it. 
You also requires `traitlets` in `setup.py` , which is an indirect dependency, I suggest removing. 

I suggest making a 
```
extras_require = dict(
 'test' = [...],
 'notebook' = [...]
 'jupyter' = [...]
)
```

if you want to.

Does it needs `jupyter nbextension enable vega --py --sys-prefix`  as said during the installation step (a word on that might be good)

Installation when smoothly ; It works.

- I was confuse the docs in `notebooks`, I was searching for `docs/notebook`.

- I'm confused by the dotted line around graph, and the fact that save freeze the graph as PNG (but I might have  bad ipywidgets)

- The colors and style looks great. 

- The PNGs looks blurry to me

 - I registed altair.readtehdocs.io, made Brian and Jake maintainer/owner.

- `.encode(...)` has a strong bytes/unicode meaning to me. 

- Same case kwargs feel weird `timeUnit`, `labelAngle`

- Examples implicitely display things as they are last cells statements, I guess people might get confused. 

- I still like the color.

- rename notebook with leading number, `Introduction` / `index` are not the firsts.

**Comment by Carreau** [comment]
`Out[1].to_dict` is **extremely confusing**

Why all the `mark_` prefix ? I'm sure there is a reason. 

I like the extreme terseness, and expresiveness.

**Comment by Carreau** [comment]
I would avoid the `from altair import *`, but personal taste.

**Comment by Carreau** [comment]
Note most of that is not relevant for RC, I'll keep adding it here, and might edit/open separate issues/thread later. 

The introduction to  `encode` and the `x='a:N'` notation might need to be a bit expanded. If I had not been here at DS4DS I would be highly confused.

**Comment by Carreau** [comment]
`You can explore the other available mark_*() methods using IPython's tab-completion.` is unacurate if one does not have Greedy completion, as `Chart(data)` will not be evaluated. 
I suggest assigning chart, once in  `Introduction.ipynb` and reusing it.

**Comment by ellisonbg** [comment]
Thanks!

* Will fix the dependencies in some way like you described. Great point.
* Rename the notebook with numeric prefix for sorting.
* @jakevdp what do you think about renaming the directory `docs`?
* Dotted line comes from the vega-lite renderer.
* We generate both a PNG and the live JS render, the auto-freeze from the PNG is form the buggy ipywidgets.
* PNGs are a bit blurry. @domoritz is it possible to create higher resolution PNGs from ipyvega?
* We are autogenerating most of the API from the JSON, which comes from JavaScript, so we are inheriting the `nonPythonicCase` of attributes.
* Great points about autocompletion, `Out[1]` and the `mark_` methods, will address that now.

**Comment by Carreau** [comment]
question:

in this example:

```
Chart(cars).mark_circle().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    size='Acceleration'
)
```


would it be possible at some future point to use:

```
Chart(cars).mark_circle().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    size=cars.Acceleration
)
```

to be smart and figure back the name of the column ?

you use the `_.<attributes>` in some places as well.

The more I read the more I like it.

**Comment by Carreau** [comment]
Vega-Lite thing comment:

for me a "circle" is not filled, a "disk" is. So the  default `mark_point`/`mark_circle` looks backward.
I **understand** that you match vega spec. I just was confused for a few seconds.

**Comment by ellisonbg** [comment]
Yes, that should be possible. It would be nice to do that as you can
autocomplete most of those and avoid typing quotes. Great idea. I will try
that now...

On Sat, Jul 9, 2016 at 5:57 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> question:
>
> in this example:
>
> Chart(cars).mark_circle().encode(
>     x='Horsepower',
>     y='Miles_per_Gallon',
>     color='Origin',
>     size='Acceleration'
> )
>
> would it be possible at some future point to use:
>
> Chart(cars).mark_circle().encode(
>     x='Horsepower',
>     y='Miles_per_Gallon',
>     color='Origin',
>     size=cars.Acceleration
> )
>
> to be smart and figure back the name of the column ?
>
> you use the _.<attributes> in some places as well.
>
> The more I read the more I like it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/140#issuecomment-231560395>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0F8x21PKv5It4pMCASrIP3nos3nEks5qUCdagaJpZM4JIt2c>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
it is possible to make module dynamically in Python, you **could** make the dataset one like that, so that users can directly use `dataset.<tab>` and dynamically fetch it on use.

**Comment by domoritz** [comment]
> PNGs are a bit blurry. @domoritz is it possible to create higher resolution PNGs from ipyvega?

PNGs are generated with a higher resolution if you have a high resolution screen. See https://github.com/vega/vega/issues/528

**Comment by ellisonbg** [comment]
@domoritz just to clarify - I am already using a retina screen and the PNGs are blurry still. Are you saying it should already work or is there something needed to get it to work?

**Comment by ellisonbg** [comment]
Releasing 1.0 now, closing...

**Comment by Carreau** [comment]
> Releasing 1.0 now, closing...

Not all things have been fixed , I for example still have blurry PNGs.
