### ISSUE TITLE
Allow columns to be specified by passing a pandas Series

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#141]
From @Carreau in #140 

```
Chart(cars).mark_circle().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    size='Acceleration'
)
```
would it be possible at some future point to use:

```Chart(cars).mark_circle().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    size=cars.Acceleration
)
```
to be smart and figure back the name of the column ?

**Comment by Carreau** [comment]
I see some reason **not** to do that, if you want the charts to be reusable. You want to avoid data reference in the spec or `encode`, see https://github.com/ellisonbg/altair/issues/143#issuecomment-231562044 as well.

**Comment by ellisonbg** [comment]
Yeah, let's wait...
