### ISSUE TITLE
Avoid usage of `_` and `Out[]` variables in docs

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#142]
This is confusing for users to who don't know these tricks in IPython.

**Comment by ellisonbg** [comment]
From @Carreau in #140

**Comment by jakevdp** [comment]
Yeah, the main reason I did this is because I wanted to follow our style of defining the chart without assigning to a variable, and also wanted to show the ``to_dict()`` method without re-typing the entire chart definition. I'm open to other suggestions, though!
