### ISSUE TITLE
Add example of without Altair/with Altair for various plotting libraries

### ISSUE THREAD

**Issue by willingc** [ellisonbg/altair#152]
One of the things that I have always liked about the [Requests README](https://github.com/kennethreitz/requests/blob/master/README.rst) is the example at the start that contrasts using requests with not using requests.

It might be cool to do the same with Altair and without Altair with the Python plotting libraries.

**Comment by ellisonbg** [comment]
LOL, yes, that would be fun. The challenge would be to come up with an
example that is simpler enough that the non-Altair version wasn't too
difficult to write ;-)

A possibility:

* Cars dataset
* mark_point
* scatterplot
* grouped by color
* facet by rows

On Sat, Jul 9, 2016 at 8:49 PM, Carol Willing <notifications@github.com>
wrote:

> One of the things that I have always liked about the Requests README
> <https://github.com/kennethreitz/requests/blob/master/README.rst> is the
> example at the start that contrasts using requests with not using requests.
>
> It might be cool to do the same with Altair and without Altair with the
> Python plotting libraries.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/152>, or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0KFn7Y9VPV3JLuWW8twUQ668-SwYks5qUE-WgaJpZM4JIvhs>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
I like it! Here's a simple one:
```python
from altair import Chart, load_dataset

# data is loaded as a pandas DataFrame
cars = load_dataset('cars')

Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```
![vega 5](https://cloud.githubusercontent.com/assets/781659/16716558/8bf85b4c-46b4-11e6-8857-3477006c1e10.png)
```python
import matplotlib.pyplot as plt

def scatter(group):
    plt.plot(group['Horsepower'], group['Miles_per_Gallon'],
             'o', label=group.name)

cars.groupby('Origin').apply(scatter)
plt.legend(title='Origin')
plt.xlabel('Horsepower')
plt.ylabel('Miles_per_Gallon');
```
![hgaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/781659/16716560/9b4b0720-46b4-11e6-9e2d-4d66e90238fa.png)

Adding facets would definitely make the matplotlib/pandas version

**Comment by ellisonbg** [comment]
Perfect! I will add this to a notebook - and probably also my talk

On Sun, Jul 10, 2016 at 5:57 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I like it! Here's a simple one:
>
> from altair import Chart, load_dataset
> # data is loaded as a pandas DataFrame
> cars = load_dataset('cars')
>
> Chart(cars).mark_point().encode(
>     x='Horsepower',
>     y='Miles_per_Gallon',
>     color='Origin',
> )
>
> [image: vega 5]
> <https://cloud.githubusercontent.com/assets/781659/16716558/8bf85b4c-46b4-11e6-8857-3477006c1e10.png>
>
> import matplotlib.pyplot as plt
> def scatter(group):
>     plt.plot(group['Horsepower'], group['Miles_per_Gallon'],
>              'o', label=group.name)
>
> cars.groupby('Origin').apply(scatter)
> plt.legend(title='Origin')
> plt.xlabel('Horsepower')
> plt.ylabel('Miles_per_Gallon');
>
> [image: hgaaaaasuvork5cyii]
> <https://cloud.githubusercontent.com/assets/781659/16716560/9b4b0720-46b4-11e6-9e2d-4d66e90238fa.png>
>
> Adding facets would definitely make the matplotlib/pandas version
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/152#issuecomment-231616006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0DbrEeBzNIHXkwZyC7zF7CuLSWKyks5qUXjygaJpZM4JIvhs>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Adding to the Index notebook in master. Closing.
