### ISSUE TITLE
Consider using requests instead of urllib

### ISSUE THREAD

**Issue by willingc** [ellisonbg/altair#153]
In `altair/datasets/core.py` it might be simpler to use requests.

**Comment by ellisonbg** [comment]
I *love* requests, but in this case the stuff we are doing is super simple
so I am not too worried about it.

On Sun, Jul 10, 2016 at 5:31 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I'm +0 on that... I would avoid additional dependencies unless there's a
> very good reason to add them. Do you have in mind any situation in which
> the current code would fail?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/153#issuecomment-231614875>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0F9_K7NsOt2rUt9fENX5893T9roQks5qUXLPgaJpZM4JIvnw>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
