### ISSUE TITLE
Move notebooks into Python package?

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#154]
I have created a `tutorial` function that downloads the documentation notebooks from github and puts them into the users cwd. This makes it really easy for a user to grab the notebooks and play with Altair using:

```python
from altair import tutorial
tutorial()
```

However, right now I am downloading the notebooks from github. If we moved the notebooks into the Python package, it solves a couple of problems:

* We can always know that the right version of the notebooks will be used by the user and don't have to keep updating the github URL to track the right commit/tag for the release.
* No internet required for a user to grab the example notebooks.
* Eventually, ipython/jupyter will likely have the ability to allow users to see/explore notebook based documentation. The mostly likely discovery mechanism will be entry points. Moving notebooks inside the package makes this an easy transition.

Eventually, imagine a magic that works like this:

```python
%nbdoc altair
```

Or 

```python
%nbdoc sklearn
```

The only downside is that a user won't see a top level notebooks directory. But we could keep it and put a README that points the user to the notebooks inside the package.

@fperez @jakevdp @willingc @Carreau

**Comment by willingc** [comment]
Nice! Pretty cool to open in JLab since the file browser improves the user experience.

Might make sense to standardize on `tutorial-altair` or `tutorial_altair` directory so if you had multiple tutorials that they would show up in the same area of the JLab file browser.

**Comment by willingc** [comment]
Also might make for a very cool RISE and tutorial mashup.

**Comment by jakevdp** [comment]
I'd be fine with wrapping them in, as long as it's clear where to find them from the README & other documentation pages.

**Comment by ellisonbg** [comment]
Done in master, updating all links now, closing.

On Sun, Jul 10, 2016 at 5:29 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I'd be fine with wrapping them in, as long as it's clear where to find
> them from the README & other documentation pages.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/154#issuecomment-231614786>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0MTsR-aJO3CRr7bQfJr_iwUQc6xHks5qUXJdgaJpZM4JIvvO>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
