### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#155]
Tried installing in a clean environment. A couple issues:

- when running ``pip install altair``, ``jupyter`` is not installed, so the next command results in an error. We should either make jupyter a requirement, or mention that it should be installed separately.
- when running ``conda install altair``, the user needs to be pointing at the ``conda-forge`` channel. This won't work until we merge the conda-feedstock PR.

**Comment by ellisonbg** [comment]
For now I left jupyter off the setup/requirement and put a note in the installation instructions.

conda instructions fixed too.
