### ISSUE TITLE
Altair doesn't handle column names with dashes in the name

### ISSUE THREAD

**Issue by littlea1** [ellisonbg/altair#169]
Altair has no output if the column name has a dash (-) in the name. Try the following:

#### This will work
xd = pd.DataFrame({'Y': {0: 17.81, 1: 22.35, 2: 25.13, 3: 16.76},
 'X': {0: '0-12', 1: '12-36', 2: '36-60', 3: '>60'}})

Chart(xd).mark_bar().encode(
    x='X:N',
    y='Y:Q',
)
#### The following won't
xd1 = pd.DataFrame({'Y-10': {0: 17.81, 1: 22.35, 2: 25.13, 3: 16.76},
 'X': {0: '0-12', 1: '12-36', 2: '36-60', 3: '>60'}})

Chart(xd1).mark_bar().encode(
    x='X:N',
    y='Y-10:Q',
)

**Comment by jakevdp** [comment]
Thanks for the comment! If you check ``chart.to_dict()``, you'll see that Altair is producing the correct JSON output; the problem is that the vega-lite renderer isn't handling this. I've reported this issue at https://github.com/vega/vega-lite/issues/778
