### ISSUE TITLE
Geographic Maps

### ISSUE THREAD

**Issue by jhmarcus** [ellisonbg/altair#170]
Does altair / vega-lite plan to support plotting on geographic maps? Faceting maps would be extremely powerful for my research and I imagine for others as well. Thanks for a great project!

Cheers,

Joe

**Comment by jakevdp** [comment]
Hi Joe – mapping is not currently in vega-lite, though it is [on the roadmap](https://github.com/vega/vega-lite/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.x+Maps%22). In the meantime, you might check out [vincent](https://vincent.readthedocs.io/en/latest/), though unless I'm mistaken that project is no longer supported.

**Comment by jheer** [comment]
I can confirm that geo-support for Vega-Lite is being actively worked on,
but we do not have a fixed release date yet. Thanks for the request!

**Comment by jhmarcus** [comment]
Fantastic! thanks @jakevdp and @jheer
