### ISSUE TITLE
Set axis range and absolute chart width

### ISSUE THREAD

**Issue by klonuo** [ellisonbg/altair#173]
Hi,

can please someone tell me how to limit the range of y-axis to [50, 100] for example?

Also is there option to set chart absolute dimensions in pixels?

Thanks

**Comment by jakevdp** [comment]
Hi,
These things are not all that well documented in Altair itself at the moment (we're working on that), but you can find info by searching for how things are done in Vega-Lite.

For example, take a look at this chart:

```python
from altair import *

# load data as a pandas DataFrame
cars = load_dataset('cars')

chart = Chart(cars).mark_point().encode(
    y='Miles_per_Gallon',
    x='Horsepower',
    color='Origin',
)

chart
```
![vega 10](https://cloud.githubusercontent.com/assets/781659/17760473/cdce98d8-64b4-11e6-8685-abd0c05f0ba5.png)

You can adjust the plot size in pixels using the ``configure_cell`` command:

```python
chart.configure_cell(height=200, width=200)
```
![vega 11](https://cloud.githubusercontent.com/assets/781659/17760492/eaed9f86-64b4-11e6-8f2d-5b13ca9c2fb7.png)

And you can adjust the axis limits using the ``domain`` subfield of the ``axis``:

```python
chart.encode(Y('Miles_per_Gallon', scale=Scale(domain=[-100, 100])))
```
![vega 12](https://cloud.githubusercontent.com/assets/781659/17760538/5bb41c9a-64b5-11e6-8c50-957ec9b11cd3.png)

Until we mirror the full vega-lite docs in Altair, you can learn more at the [Vega-Lite docs](https://vega.github.io/vega-lite/docs/). The translation is pretty strightforward: JSON fields in Vega-Lite become Python attributes in Altair.

**Comment by klonuo** [comment]
Excellent. Thanks for your time and walkthrough.

**Comment by DSLituiev** [comment]
it might be implied / intended, but in my hands the `scale=Scale()` does limit the ticks and box, but outliers I aim to exclude with this command are still displayed and I get a huge blank space above my graph like below. As a user, when I am set axis limits, I usually want no outliers to be displayed at all. Is there a chance to change the behaviour?

![image](https://cloud.githubusercontent.com/assets/8426290/25050858/8f62abe6-20fe-11e7-97d2-2effa728603f.png)

**Comment by jakevdp** [comment]
Altair/Vega-Lite will not filter-out data points unless you explicitly ask it to. The config docs have some discussion of how to get around this: https://altair-viz.github.io/documentation/config.html#adjusting-axis-limits

**Comment by DSLituiev** [comment]
Thank you! Unfortunately I get complete nonsense when my data is of `temporal` type:
```python
x_ = 'year'
y_ = 'num_citations'

xrange = [1980, 2020]
# data = data[data[x_]<xrange[-1]]
yrange = [0, 1.6e3]
# data = data[data[y_]<yrange[-1]]

chart = Chart(data[[x_, y_]].dropna()).mark_point().encode(
    x=X(x_, scale=Scale(domain=xrange, clamp=True),
        type="temporal", timeUnit="year",  # when this line is commented it's OK 
        title="year"),  
    y=Y(y_, scale=Scale(domain=yrange, clamp=True), title="number of citations"),
#     color='r',
)
# chart.configure_axis?
chart.display()
```
![image](https://cloud.githubusercontent.com/assets/8426290/25051642/8bbcd8be-2102-11e7-9707-2ee7faf5a528.png)

**Comment by jakevdp** [comment]
Yeah... I recall this being an issue, and somewhere I submitted a related bug report to vega-lite – if I recall correctly, when referencing temporal data you currently need to use the internal representation of the data, which is some integer number of nanoseconds I believe. I'll see if I can find the reference to that issue
   Jake

**Comment by jakevdp** [comment]
This is what I was thinking of: https://github.com/altair-viz/altair/issues/187

The conversion here is what you need: https://github.com/altair-viz/altair/issues/187#issuecomment-244126070

Basically, you need to specify axis limits and filters in seconds since the zero-point, which is around 1970 I think.

From what I've heard, this issue will be addressed in the next release of Vega-Lite & Altair.

**Comment by jwhendy** [comment]
Is there a reason that `chart.configure_cell()` would not work with `mark_bar`?

Modifying your example above:

```
import altair as alt
alt.enable_mime_rendering()

cars = alt.load_dataset('cars')
cars = cars.iloc[0:5]
chart = alt.Chart(cars).mark_bar().encode(
    y='Miles_per_Gallon',
    x='Name',
)

chart

```

![2017-12-22_205227](https://user-images.githubusercontent.com/379357/34316388-0ffc64f0-e75a-11e7-9709-faa4f877d2b1.png)


```
chart.configure_cell(height=200, width=800)
```

![2017-12-22_205234](https://user-images.githubusercontent.com/379357/34316389-131597f6-e75a-11e7-876f-7b7eeaa058e2.png)

The specification appears to shrink the height, but it doesn't widen it. I just wanted to beef up the bars. No particular reason, just looks skinny to me. Here's the `ggpy` equivalent for reference.

![2017-12-22_205344](https://user-images.githubusercontent.com/379357/34316399-45168814-e75a-11e7-936b-ab12985ac5ed.png)

**Comment by brainstorm** [comment]
Is `.configure_cell()` not supported anymore in altair 2.0.1?:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-09fe7b9dd3ab> in <module>()
     21 )
     22 
---> 23 sample_chart.configure_cell(height=200, width=200)
     24 
     25 sample_chart | tech_chart | logplot

~/.miniconda/envs/testing-altair/lib/python3.6/site-packages/altair/utils/schemapi.py in __getattr__(self, attr)
    173             except AttributeError:
    174                 _getattr = super(SchemaBase, self).__getattribute__
--> 175             return _getattr(attr)
    176 
    177     def __setattr__(self, item , val):

AttributeError: 'Chart' object has no attribute 'configure_cell'
```

**Comment by jakevdp** [comment]
Correct, most everything in this issue refers to version 1 and does not work on version 2. The documentation details how to customize charts in version 2.

**Comment by feliperoque** [comment]
Hi mates, i'm trying to do the same process as @klonuo was in doubt. Following the answer given by @jakevdp i did as you can see below. Where new_df are in the image below:


![121212](https://user-images.githubusercontent.com/34341242/114973418-d2721500-9e56-11eb-936f-78dc6c2a0a1f.PNG)


First i created two dataframes (as you can see) to add at _alt.scale_ fuction as my minimum and maximum range values from _media_ column. After, i put both at _alt.Scale_  in  _Y axis_ configuration and get in return the following chart (this time correct; as i have in each column very close values to each other, i was getting before a chart with line under line). 

However, in the chart below you can see he is not showing the data range from column _amostra_ (which is from one to twenty). A way i can see,  was repeat the same process i did in _Y axis_ case, so i created two more dataframe with the maximum and minimum from _amostra_ column and pass both to _X axis_ expecting to work, but didn't worked....he didn't show odd points only the evens one, how can i fix this?

![12121212](https://user-images.githubusercontent.com/34341242/114974521-ea4a9880-9e58-11eb-97bf-0ae467673e2a.PNG)




```
y_range_max_1 = new_df['media'].max()
y_range_min_1 = new_df['media'].min()

x_range_max_1 = new_df['amostra'].max()
x_range_min_1 = new_df['amostra'].min()

base = alt.Chart(new_df)

base_chart = base.mark_line(point=True,color='red').encode(
    alt.X('amostra',scale=alt.Scale(domain=(x_range_min_1,x_range_max_1))),
    alt.Y('media',scale=alt.Scale(domain=(y_range_min_1,y_range_max_1)))
    
)
```

**Comment by joelostblom** [comment]
By default, the domain is set to align nicely to the ticks on the axis. If you want to ignore that and start at the exact numbers your are passing to the domain, you can specify `nice=False` in side `alt.Scale`
