### ISSUE TITLE
[InstallNBExtensionApp] CRITICAL | Unrecognized flag: '--sys-prefix'

### ISSUE THREAD

**Issue by Vaibhavs10** [ellisonbg/altair#175]
Hey!

I am using python 2.7 and I have been trying to install altair on my local machine but every time I try do the same it throws this error 

[InstallNBExtensionApp] CRITICAL | Bad config encountered during initialization:
[InstallNBExtensionApp] CRITICAL | Unrecognized flag: '--sys-prefix'

My Jupyter notebook is up to date but still, I can't seem to find the reason for the same.

TIA :)

**Comment by jakevdp** [comment]
Hi,
This was our mistake – the ``--sys-prefix`` flag only works in the most recent release of Jupyter. If you update jupyter before installing, the error should go away.

**Comment by jakevdp** [comment]
I'm going to close this as a duplicate of https://github.com/ellisonbg/altair/issues/156

**Comment by Vaibhavs10** [comment]
I ran pip install --upgrade notebook still it throws the same error!

**Comment by jakevdp** [comment]
Huh... what is the result of ``jupyter nbextension --version``?

**Comment by Vaibhavs10** [comment]
Hey! 

It says 4.1.0

Even after the upgrade.

**Comment by jakevdp** [comment]
What are the outputs of the following?

```
$ which python
$ which pip
$ which jupyter
``

**Comment by Vaibhavs10** [comment]
which python:
/home/vaibhav/anaconda2/bin/python

which pip:
/home/vaibhav/anaconda2/bin/pip

which jupyter:
/home/vaibhav/anaconda2/bin/jupyter

**Comment by jakevdp** [comment]
Oh, you're using anaconda. Try ``conda update notebook`` first.

**Comment by Vaibhavs10** [comment]
Worked like a charm! I feel so stupid now. Thanks a lot :D

**Comment by jakevdp** [comment]
No worries! Hopefully by the next release, we'll have appropriate versions in the dependencies so ``conda install`` will work every time.

**Comment by marvinxu-free** [comment]
i used conda update notebook and my notebook version is 5.0.0, this still not work
@jakevdp
