### ISSUE TITLE
Add html render?

### ISSUE THREAD

**Issue by freeman-lab** [ellisonbg/altair#18]
I think I've hacked together a combo of vega 1.x + vega-lite that I think will embed rendered html based on the specs we generate :pray: . Worth adding here alongside the `render`,  maybe as a `render_html`? Probably just for intermediate testing purposes, while we wait for vega-lite 2.x support and/or incorporation it into other interactive libraries (e.g. Lightning).

**Comment by ellisonbg** [comment]
Merged!

**Comment by ellisonbg** [comment]
Merged, trying again...
