### ISSUE TITLE
problem about axis scale

### ISSUE THREAD

**Issue by icrtiou** [ellisonbg/altair#191]
I face this problem.

The raw data in Vega source looks like this:
```json
"data": {
    "values": [
      {
        "epoch": 0,
        "cost": 0.48936170212765956
      },
      {
        "epoch": 1,
        "cost": 0.2800426842405414
      },
      {
        "epoch": 2,
        "cost": 0.20792379484603637
      },
      {
        "epoch": 3,
        "cost": 0.17867527994274826
      },
      ......
```
I use this code to produce graph in jupyter notebook
```python
c = Chart(df).mark_line().encode(
        x='epoch',
        y='cost')
```
but as you can see in the final rendering graph, the y scale is very weird.
![wrong_y_scale](https://cloud.githubusercontent.com/assets/1643232/18255399/3c0892ce-735e-11e6-9201-736a0037555b.png)

What's going on here? How to fix it?
Thanks.

**Comment by jakevdp** [comment]
I see that as well. For reference, here's an encapsulated example script:

```python
from altair import *
import pandas as pd
df = pd.DataFrame({'epoch': [0, 1, 2, 3, 4],
                   'cost': [0.48, 0.28, 0.21, 0.18, 0.17]})

Chart(df).mark_line().encode(
        x='epoch',
        y='cost')
```
![vega 16](https://cloud.githubusercontent.com/assets/781659/18256250/8cf38956-7367-11e6-98f6-844b254d9201.png)

This seems to be a default choice made by Vega-lite itself, and so it might be worth raising an issue there. For what it's worth, if the data goes above 1.0, the labels are what you might expect:
```python
df = pd.DataFrame({'epoch': [0, 1, 2, 3, 4],
                   'cost': [1.48, 0.28, 0.21, 0.18, 0.17]})

Chart(df).mark_line().encode(
        x='epoch',
        y='cost')
```
![vega 17](https://cloud.githubusercontent.com/assets/781659/18256263/c7343962-7367-11e6-86d8-14d2515540d6.png)

Maybe @kanitw or @domoritz would know why this choice of format is made.

**Comment by jakevdp** [comment]
One other note: if you'd like to specify a particular format manually, you can use the ``Axis(format=`` attribute:
```
df = pd.DataFrame({'epoch': [0, 1, 2, 3, 4],
                   'cost': [0.48, 0.28, 0.21, 0.18, 0.17]})

Chart(df).mark_line().encode(
        x='epoch',
        y=Y('cost', axis=Axis(format='f')))
```
![vega 18](https://cloud.githubusercontent.com/assets/781659/18256318/929e86b6-7368-11e6-8aa6-76f1e4ccdee8.png)

The format is specified as any [d3 format code](https://github.com/d3/d3-format/blob/master/README.md#format).

**Comment by icrtiou** [comment]
Got it! Thanks for the pointers. @jakevdp

**Comment by kanitw** [comment]
We'll definitely revise default Vega-Lite axis format in 2.0 release.  
I just created an issue here: https://github.com/vega/vega-lite/issues/1539.
