### ISSUE TITLE
Add chart titles

### ISSUE THREAD

**Issue by areaweb** [ellisonbg/altair#192]
Is there a way to add a title to the chart? If not, could there be?

**Comment by jakevdp** [comment]
I don't think there is. You could put in a feature request on Vega-Lite; Altair doesn't define any plot elements itself.

**Comment by jakevdp** [comment]
Of course, since the resulting chart is (usually) rendered in HTML, you can always add an HTML title that would appear above the chart.

**Comment by areaweb** [comment]
Got it, thanks for the reply.

**Comment by jakevdp** [comment]
I looked through the Vega-Lite issues; it looks like chart titles are on their radar: https://github.com/vega/vega-lite/issues/431

**Comment by Ricardo-C-Oliveira** [comment]
It looks like title was implemented in Vega-Lite, does it means that is also available in Altair?

**Comment by jakevdp** [comment]
It will be once Altair 2.0 is released. I'm working on that at the moment: https://github.com/altair-viz/altair/pull/374

**Comment by deisi** [comment]
So is this implemented now?

**Comment by deisi** [comment]
Ah it's a property. Okay thx.

Am 22. Mai 2018 12:23:31 MESZ schrieb afonit <notifications@github.com>:
>@deisi , yes, here is an example that uses it:
>https://github.com/altair-viz/altair/blob/4c344e79ebf619e762d5d220caab1b7a58996ac5/altair/vegalite/v2/examples/line_percent.py
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/altair-viz/altair/issues/192#issuecomment-390940928

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
