### ISSUE TITLE
Warning on `df==None`

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#34]
When the `data` attribute of a `Viz` class changed, traitlets does a `df==None` test to see if the value has changed. This raises a warning.

**Comment by jakevdp** [comment]
I wonder if [numtraits](https://github.com/astrofrog/numtraits) might be able to better handle this?

**Comment by ellisonbg** [comment]
I talked to some of the traitlets debs yesterday and there is an easy way of dealing with this. I can submit a PR.

**Comment by jakevdp** [comment]
Great!

**Comment by ellisonbg** [comment]
I have implemented a simple DataFrameTrait, and it has fixed some of these warnings, but I am still seeing some of them. Will investigate further.

**Comment by ellisonbg** [comment]
For now I am going to close this. Here is how we are handling it:

* Make sure we don't ever compare a `DataFrame` to `None`. Instead, we are using `isinstance`.
* Using a property to hold the `DataFrame` rather than trait.
