### ISSUE TITLE
Finish implementing rest of JSON spec

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#42]

**Comment by aggFTW** [comment]
I'm looking for a first work item to start contributing to the project. Do you think this would be appropriate?

I think @alope107 was working on this. Is this still available?

**Comment by alope107** [comment]
This is a good place to start, and is still available. I very briefly looked into this, but haven't yet put any real work into it.

**Comment by aggFTW** [comment]
Ok, let me try my hand at this then. Thanks @alope107!

**Comment by aggFTW** [comment]
I'm trying to run some of the sample notebooks, namely ChartExamples, created by @wrobstory.
I am running into the following error when trying to visualize the chart though:

```
<ipython-input-6-4caceaca6d6b> in <module>()
----> 1 out = html.render(fig_1)
      2 display(HTML(html.render(fig_1)))

...

/Users/alexgg/anaconda/lib/python2.7/site-packages/jinja2/loaders.pyc in get_source(self, environment, template)
    223         p = '/'.join((self.package_path,) + tuple(pieces))
    224         if not self.provider.has_resource(p):
--> 225             raise TemplateNotFound(template)
    226 
    227         filename = uptodate = None

TemplateNotFound: template.html
```

It's a jinja2 error but I cannot figure out what I´m doing wrong. Do you know how to solve this @alope107?

On a side note, I also had to do pip install traitlets before I could find the Configurable class. The try/catch block on the import in api.py did not work to import it.

Thanks!

**Comment by ellisonbg** [comment]
I have a PR that fixes a bunch of stuff in the works, why don't you let my
push that first tomorrow....

On Mon, Oct 5, 2015 at 9:06 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> I'm trying to run some of the sample notebooks, namely ChartExamples,
> created by @wrobstory <https://github.com/wrobstory>.
> I am running into the following error when trying to visualize the chart
> though:
>
> <ipython-input-6-4caceaca6d6b> in <module>()
> ----> 1 out = html.render(fig_1)
>       2 display(HTML(html.render(fig_1)))
>
> ...
>
> /Users/alexgg/anaconda/lib/python2.7/site-packages/jinja2/loaders.pyc in get_source(self, environment, template)
>     223         p = '/'.join((self.package_path,) + tuple(pieces))
>     224         if not self.provider.has_resource(p):
> --> 225             raise TemplateNotFound(template)
>     226
>     227         filename = uptodate = None
>
> TemplateNotFound: template.html
>
> It's a jinja2 error but I cannot figure out what I´m doing wrong. Do you
> know how to solve this @alope107 <https://github.com/alope107>?
>
> On a side note, I also had to do pip install traitlets before I could find
> the Configurable class. The try/catch block on the import in api.py did not
> work to import it.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/42#issuecomment-145713593>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
Hi @ellisonbg, do you have an update on that PR?

**Comment by ellisonbg** [comment]
We are now autogenerating this python classes from the VL spec, so we are covering all of it.
