### ISSUE TITLE
Config naming confusion

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#53]
Now that all of our classes are inheriting from traitlets `Configurable`, they have a `config` property. What we didn't notice is that Viz objects in the VL spec also have a `config` property. These two notions of config are completely separate, but have the same property names, which conflixts. To get around this I have called the VL config property `Viz/vlconfig` but make sure that it still gets serialized to `config` in `to_dict`. I am not too fond of this, but don't have a better idea at this point. Any ideas?

@jakevdp @wrobstory @tacaswell

**Comment by jakevdp** [comment]
That's a tough one... I'll think about it a bit.

**Comment by tacaswell** [comment]
That will make things difficult if we want to pass the python objects into `render` rather than the exported dictionaries.

**Comment by ellisonbg** [comment]
Great point Thomas. I can write a small class that is like Configurable and
has a different name for this. Maybe `settings`?

On Sun, Sep 20, 2015 at 3:19 PM, Thomas A Caswell <notifications@github.com>
wrote:

> That will make things difficult if we want to pass the python objects into
> render rather than the exported dictionaries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/53#issuecomment-141841166>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
> Maybe `settings`?

+1 on that.

**Comment by ellisonbg** [comment]
In the revised API in master swe are no longer using Configurable at all so there is no conflict.
