### ISSUE TITLE
Spec for boxplots

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#57]
Starting to think about how to express a box plot with this type of spec. For this discussion, let's say we have two columns: `amount:Q` and `state:N`.

Option 1 (boxplot implies computing the summary stats):

```
Vis(df).encode(x='state:N', y='amount:Q').boxplot()
```

Option 2 (explicit summary stats call):

```
Vis(df).encode(x='state:N', y='summarize(amount):Q').boxplot()
```

The big change from the existing vega-lite spec is that a box plot requires more than a scalar aggregation of the y data (mean, var, etc.). Questions:

* Should aggregations be able to emit non-scalars?
* Should marks be able to comsume non-scalars (either entire data sets or non-scalar aggregations)?

**Comment by jakevdp** [comment]
Is this in scope here? Vega-lite doesn't support boxplots yet, does it?

**Comment by ellisonbg** [comment]
Sorry I wasn't clear. That was the point - I would like vega-lite to
support boxplots and wanted to begin exploring what that might look like

On Tue, Sep 22, 2015 at 10:35 AM, Jake Vanderplas <notifications@github.com>
wrote:

> Is this in scope here? Vega-lite doesn't support boxplots yet, does it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/57#issuecomment-142357782>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Got it!

**Comment by kanitw** [comment]
We haven't designed the syntax for boxplot, but have an opening issue here https://github.com/vega/vega-lite/issues/220.

**Comment by ellisonbg** [comment]
Going to close this as it is really a vega-lite question and there are good alternatives already.
