### ISSUE TITLE
Wrapping JS libraries (Like R HTML widgets)

### ISSUE THREAD

**Issue by datnamer** [ellisonbg/altair#62]
JS has lots of great specialized libraries. [HTML Widgets](http://www.htmlwidgets.org/) wraps them in R.

Maybe Altair can have similar facilities. Is this in scope?

**Comment by ellisonbg** [comment]
That would be more of the scope of ipython/ipywidgets

Altair is narrowly focused on a small subset of the overall visualization
space.

That isn't to say that wrapping HTML/JS libraries in Python isn't a good
idea though - it is definitely where all this is headed.

On Thu, Sep 24, 2015 at 1:07 PM, datnamer <notifications@github.com> wrote:

> JS has lots of great specialized libraries. HTML Widgets
> <http://www.htmlwidgets.org/> wraps them in R.
>
> Maybe Altair can have similar facilities. Is this in scope?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/62>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by datnamer** [comment]
Cool!

Should I open an issue there?

**Comment by datnamer** [comment]
@ellisonbg With the 1.0 release of vega, I'm again looking at using this library. Will it be maintained or worked on or should I look for an alternative?

**Comment by ellisonbg** [comment]
I do plan on adding vega-lite 1.0 support soon

I would love to start to ship the 1.0 vega-lite JS with this as well using
some of the new Jupyter nbextension stuff.

...any help welcomed...

On Wed, Feb 24, 2016 at 4:24 PM, datnamer <notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> With the 1.0 release of vega,
> I'm again looking at using this library. Will it be maintained or worked on
> or should I look for an alternative?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/62#issuecomment-188532388>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
Nice to hear that.  

cc: @domoritz

**Comment by datnamer** [comment]
@ellisonbg Great! I don't know much about javascript, but how can i help?

**Comment by ellisonbg** [comment]
Here is a rough sketch:

We would use the embedding approach described here:

http://vega.github.io/vega-lite/docs/embed.html

Along with IPython.display.Javascript to render the JSON spec produced by
Altair in the Jupyter notebook.

The actual JavaScript would be treated as an IPython/Jupyter nbextension. A
good example of how that works can be found in this example:

https://github.com/jdfreder/jupyter-lightsaber

The other thing you could work on is updating Altair to follow the official
vega-lite 1.0 spec. Probably best to create a few issues in the repo to let
us track this stuff.

Cheers,

Brian



On Wed, Feb 24, 2016 at 4:53 PM, datnamer <notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> Great! I don't know much about
> javascript, but how can i help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/62#issuecomment-188539172>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by domoritz** [comment]
Fantastic. I was actually looking into this today but gave up because I couldn't find any good documentation of best practices. I'll pick it up again with the suggestion from @ellisonbg. 

I'm going to create a little vega-lite nbextension in https://github.com/vega/ipython-vega. For now it won't use altair though and instead just take a python dictionary that is directly translated to a json.

**Comment by ellisonbg** [comment]
Great, I think it would be great to have vega/vega-lite maintain the
ipython nbextensions that take raw python dicts and render them in the
notebook using vega/vega-lite. Then altair can just rely on that
ipython-ega and generate those dicts.

One important point, that example of an nbextension that I pointed to
relies on this PR that will be merged in the jupyter/notebook 4.2 release:

https://github.com/jupyter/notebook/pull/879

That PR basically makes it much easier to install, enable and disable
nbextensions. The 4.2 release should be out in the next few weeks. Please
reach out here if you run into issues or questions.

Cheers,

Brian


On Wed, Feb 24, 2016 at 8:21 PM, Dominik Moritz <notifications@github.com>
wrote:

> Fantastic. I was actually looking into this today but gave up because I
> couldn't find any good documentation of best practices. I'll pick it up
> again with the suggestion from @ellisonbg <https://github.com/ellisonbg>.
>
> I'm going to create a little vega-lite nbextension in
> https://github.com/vega/ipython-vega. For now it won't use altair though
> and instead just take a python dictionary that is directly translated to a
> json.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/62#issuecomment-188607481>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by domoritz** [comment]
I tried to get your version of the notebook. I check out your branch and ran `pip install --pre -e .`. 

Launching the jupyter notebook throws an error though.

```
Traceback (most recent call last):
  File "/Users/domoritz/.virtualenvs/ipython/bin/jupyter-notebook", line 9, in <module>
    load_entry_point('notebook', 'console_scripts', 'jupyter-notebook')()
  File "/Users/domoritz/.virtualenvs/ipython/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/domoritz/.virtualenvs/ipython/lib/python2.7/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/domoritz/.virtualenvs/ipython/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/domoritz/Developer/UW/notebook/notebook/notebookapp.py", line 1054, in initialize
    self.init_webapp()
  File "/Users/domoritz/Developer/UW/notebook/notebook/notebookapp.py", line 891, in init_webapp
    self.jinja_environment_options
  File "/Users/domoritz/Developer/UW/notebook/notebook/notebookapp.py", line 145, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/Users/domoritz/Developer/UW/notebook/notebook/notebookapp.py", line 200, in init_settings
    nbextensions=ipython_app.nbextensions,
AttributeError: 'NotebookApp' object has no attribute 'nbextensions'
```

What can I do?

**Comment by ellisonbg** [comment]
Hmm, @jdfreder can you look at this. @domoritz is trying to run the nbextension PR https://github.com/jupyter/notebook/pull/879

**Comment by domoritz** [comment]
Also, I'm still struggling to find any example or documentation about how to get css, js and html into a notebook. https://github.com/jdfreder/jupyter-lightsaber seems to be embedding the css in the js itself and then adding a script tag to the body manually. Is this the best practice with nbextensions or is there some way to tell the notebook to load some css and css?

The next question I have is how I would I load the html needed to display a visualization in a new cell/ below a cell?

Let me try to describe what I think and whether I'm on the right track. 

The goal is an extension for Jupyter that when provided with a vega-lite spec, renders that spec in the output of a cell in the notebook. Now the question is how would the user initiate this? The first option is a special cell type (similar to the markdown) that takes only the spec itself. The second option is some python code that can be called and produces the visualization as output. Something like 

```python
from vega import vegalite
vegalite.display(spec)
```

I personally prefer the former from a user perspective, though. 

So what we need is some css, and js loaded. Also, we need some functionality that crates some html in the output of a cell to wrap the visualization. This could be as little as

```html
<div class="vega-embed" data-type="vega-lite">
{
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
</div>
```

The javascript code could automatically pick this up. 

I heard some rumors that Jupyter won't allow javascript in the notebook but instead would wrap the output of a cell in an iframe, which in turn can load it's own css, js and html. I already implemented this aproach in https://github.com/vega/ipython-vega/blob/master/vega/tool.py but it seemed very hacky. The big issue with this approach is that each cell increases the size of the notebook by a few megabytes. Also, the complete blob of html with embedded css/ js/ images as base64 is stored in the json notebook file. I wonder whether there is a cleaner way to load dependencies (specifically js and css)?

One way to get to the behavior described above but without the iframe would be to split the extension into two parts. a) Some python code to output the html described above when the right command is called. Something similar could easily be implemented in other languages. b) An nbextension that loads the js (and css?).

Does this sound right? Do I have to worry about the iframe issue? 

Even better would be of course something like https://github.com/ramnathv/htmlwidgets where you can easily specify the dependencies. But then, htmlwidgets is for widgets and not general extensions so I guess nbextensions/ https://github.com/jupyter/notebook/pull/879 are more powerful.

**Comment by domoritz** [comment]
http://nbviewer.jupyter.org/github/vega/ipython-vega/blob/master/Vega-Lite.ipynb

as prototyped in https://github.com/vega/ipython-vega/commit/223af2683e30b1e8446020d6184f443c72f4460a

**Comment by ellisonbg** [comment]
It would be great to get this out of the iframe as it isn't needed. A few
questions:

* Is it possible to use webpack or browserify to bundle up all the JS
(including d3, etc.) into a single file that we can load using require.js?
If we can do that, then getting it onto the page is pretty easy. There are
some benefits to using the iframes though in terms of isolating from the
rest of the page, but it does make some things a real pain.
* Are the .js files that ship in the repos that latest stable builds? Is it
easy to just npm require everything and go that route?

Cheers,

Brian

On Wed, Feb 24, 2016 at 11:20 PM, Dominik Moritz <notifications@github.com>
wrote:

>
> http://nbviewer.jupyter.org/github/vega/ipython-vega/blob/master/Vega-Lite.ipynb
>
> as prototyped in vega/ipython-vega@223af26
> <https://github.com/vega/ipython-vega/commit/223af2683e30b1e8446020d6184f443c72f4460a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/62#issuecomment-188648039>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by domoritz** [comment]
> * Is it possible to use webpack or browserify to bundle up all the JS
(including d3, etc.) into a single file that we can load using require.js?
If we can do that, then getting it onto the page is pretty easy. There are
some benefits to using the iframes though in terms of isolating from the
rest of the page, but it does make some things a real pain.

I can certainly bundle everything but I can't get the notebook to load the plugin correctly. I messaged you on gitter to get some help.

**Comment by jdfreder** [comment]
> Hmm, @jdfreder can you look at this. @domoritz is trying to run the nbextension PR jupyter/notebook#879

The nbextension PR is still being worked on, @domoritz you probably tried it on a day where it was be reworked.  You can try again, it should be working at this moment in time.

**Comment by domoritz** [comment]
@jdfreder Yes, it's working now. Thanks!
