### ISSUE TITLE
playing BasicExample raises pandas 0.17 warning

### ISSUE THREAD

**Issue by stonebig** [ellisonbg/altair#64]
not sure if it's altair or seaborn, so I post here.
![altair_warning1](https://cloud.githubusercontent.com/assets/4312421/10411623/e98a9520-6f6b-11e5-9667-20d20b2a133d.GIF)

**Comment by jakevdp** [comment]
I think this is the same as the issue discussed here: https://github.com/ellisonbg/altair/issues/34

**Comment by ellisonbg** [comment]
Yep, we are working on it...closing this one.

On Sat, Oct 10, 2015 at 12:23 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I think this is the same as the issue discussed here: #34
> <https://github.com/ellisonbg/altair/issues/34>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/64#issuecomment-147103779>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
