### ISSUE TITLE
Are filter and config in spec methods for Viz just like encode is?

### ISSUE THREAD

**Issue by aggFTW** [ellisonbg/altair#75]
I'm having trouble understanding exactly how those should be implemented. I'll take another look tomorrow when I have a clearer head =)

**Comment by ellisonbg** [comment]
For `config` we have both an attribute and method. Right now the name of the attribute is `vlconfig` but once we fix #53 it will be `config` and `configure`.

The case of filter is different (and difficult) as `filter` is both a noun (for the attribute) and a verb (for the method). Not sure how to address that.
