### ISSUE TITLE
NaN fields produce errors with the lightning renderer - may affect other renderers too?

### ISSUE THREAD

**Issue by aggFTW** [ellisonbg/altair#80]
Using Altair to render the following pandas df:
```
records_text = '{"clientid":"8","querytime":"18:54:20","market":"en-US","deviceplatform":"Android","devicemake":"Samsung","devicemodel":"SCH-i500","state":"California","country":"United States","querydwelltime":13.9204007,"sessionid":0,"sessionpagevieworder":0}\n{"clientid":"23","querytime":"19:19:44","market":"en-US","deviceplatform":"Android","devicemake":"HTC","devicemodel":"Incredible","state":"Pennsylvania","country":"United States","sessionid":0,"sessionpagevieworder":0}'
json_array = "[{}]".format(",".join(records_text.split("\n")))
import json
d = json.loads(json_array)
result = pd.DataFrame(d)
result

```

the NaN for querydwelltime produces the following error:
```
Javascript error adding output!
TypeError: Cannot read property 'prop' of undefined
See your browser Javascript console for more details.
```

The vegalite spec produced by Altair is:
```
{'config': {'width': 600, 'gridOpacity': 0.08, 'gridColor': u'black', 'height': 400}, 'marktype': 'point', 'data': {'formatType': 'json', 'values': [{u'deviceplatform': u'Android', u'devicemodel': u'SCH-i500', u'country': u'United States', u'sessionpagevieworder': 0, u'state': u'California', u'clientid': u'8', u'sessionid': 0, u'querytime': u'18:54:20', u'devicemake': u'Samsung', u'market': u'en-US', u'querydwelltime': 13.9204007}, {u'deviceplatform': u'Android', u'devicemodel': u'Incredible', u'country': u'United States', u'sessionpagevieworder': 0, u'state': u'Pennsylvania', u'clientid': u'23', u'sessionid': 0, u'querytime': u'19:19:44', u'devicemake': u'HTC', u'market': u'en-US', u'querydwelltime': nan}]}}
```

For commentary and possible fixes, this issue is tracked by lightning renderer in:
https://github.com/lightning-viz/lightning-python/issues/34

This issue is also documented in sparkmagic at: https://github.com/jupyter-incubator/sparkmagic/issues/39

cc @mathisonian

**Comment by ellisonbg** [comment]
There is a part of the vega-lite spec that can filter out these things I
think in the .filter section.


On Fri, Oct 30, 2015 at 3:57 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Using Altair to render the following pandas df:
>
> records_text = '{"clientid":"8","querytime":"18:54:20","market":"en-US","deviceplatform":"Android","devicemake":"Samsung","devicemodel":"SCH-i500","state":"California","country":"United States","querydwelltime":13.9204007,"sessionid":0,"sessionpagevieworder":0}\n{"clientid":"23","querytime":"19:19:44","market":"en-US","deviceplatform":"Android","devicemake":"HTC","devicemodel":"Incredible","state":"Pennsylvania","country":"United States","sessionid":0,"sessionpagevieworder":0}'
> json_array = "[{}]".format(",".join(records_text.split("\n")))
> import json
> d = json.loads(json_array)
> result = pd.DataFrame(d)
> result
>
>
> the NaN for querydwelltime produces the following error:
>
> Javascript error adding output!
> TypeError: Cannot read property 'prop' of undefined
> See your browser Javascript console for more details.
>
> The vegalite spec produced by Altair is:
>
> {'config': {'width': 600, 'gridOpacity': 0.08, 'gridColor': u'black', 'height': 400}, 'marktype': 'point', 'data': {'formatType': 'json', 'values': [{u'deviceplatform': u'Android', u'devicemodel': u'SCH-i500', u'country': u'United States', u'sessionpagevieworder': 0, u'state': u'California', u'clientid': u'8', u'sessionid': 0, u'querytime': u'18:54:20', u'devicemake': u'Samsung', u'market': u'en-US', u'querydwelltime': 13.9204007}, {u'deviceplatform': u'Android', u'devicemodel': u'Incredible', u'country': u'United States', u'sessionpagevieworder': 0, u'state': u'Pennsylvania', u'clientid': u'23', u'sessionid': 0, u'querytime': u'19:19:44', u'devicemake': u'HTC', u'market': u'en-US', u'querydwelltime': nan}]}}
>
> For commentary and possible fixes, this issue is tracked by lightning
> renderer in:
> lightning-viz/lightning-python#34
> <https://github.com/lightning-viz/lightning-python/issues/34>
>
> This issue is also documented in sparkmagic at:
> jupyter-incubator/sparkmagic#39
> <https://github.com/jupyter-incubator/sparkmagic/issues/39>
>
> cc @mathisonian <https://github.com/mathisonian>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/80>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
We need to understand a few things here:

* How vega-lite/vega need NaNs encoding. But we should only do that at the final stage when to_dict is called, not before. JavaScript has limited NaN handling compared to pandas and we don't want to make NaN handling for Python based renderers more difficult.
* Implement the filter part of the spec.

**Comment by ellisonbg** [comment]
Should be fixed in master...
