### ISSUE TITLE
Lightning renderer broken inside `ipywidgets.Output`

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#82]
When trying to get the lightening renderer to work with the new IPython widget, it breaks in many ways. In particular, it won't render at all inside `ipywidget.Output`. This may be related to:

* How lightning uses IFrames
* The lack of a unique `id` on the div (should have a uuid).
* Other?

**Comment by aggFTW** [comment]
Thanks for opening this issue @ellisonbg :) Who would be the best person to look at this? I'll also post this issue in the Lightning gitter group.

**Comment by ellisonbg** [comment]
We have deprecated the lightning renderer, so closign
