### ISSUE TITLE
Integration with topological data analysis library?

### ISSUE THREAD

**Issue by datnamer** [ellisonbg/altair#83]
Here is a python [TDA](http://www.slideshare.net/paul_kyeong/topological-data-analysis-with-examples) library with a JS viz GUI: https://github.com/rosinality/knotter 

Do you think this would be in scope for exploratory data analysis in Altair?

**Comment by ellisonbg** [comment]
We really want to focus on a very narrow problem in the larger
visualization space:

1) Table based data only
2) Statistical visualizations that are intrinsically tied to various data
transformations (binning, groupby, aggregation).
3) Declarative

From a quick look, it is not obvious how TDA fits within that.

On Mon, Nov 2, 2015 at 10:34 AM, datnamer <notifications@github.com> wrote:

> Here is a python TDA
> <http://www.slideshare.net/paul_kyeong/topological-data-analysis-with-examples>
> library with a JS viz GUI: https://github.com/rosinality/knotter
>
> Do you think this would be in scope for EDA in Altair?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/83>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
