### ISSUE TITLE
Redo Unit Tests

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#88]
With the rewrite for the 1.0 spec, the unit tests are failing.

@ellisonbg – can I work on this while you're scraping the example plots this morning?

**Comment by jakevdp** [comment]
Done in https://github.com/ellisonbg/altair/commit/4a27843cb3a8132b20dd3db178cf2e3e4dac447f; I solved most of the issues by prepending an underscore to ``_test_api.py``. The API has changed enough that we'll want to re-write all of these. Let's discuss this afternoon.

**Comment by ellisonbg** [comment]
Tests are passing, but we need more to battle test the new code...closing for now...
