### ISSUE TITLE
Create conda package on conda forge

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#89]
Here is an example...

https://github.com/conda-forge/ipyleaflet-feedstock

**Comment by jakevdp** [comment]
``ipyvega`` is [on conda-forge now](https://github.com/conda-forge/vega-feedstock), so adding an ``altair`` recipe should be trivial. Releasing to PyPI and running ``conda skeleton pypi altair`` should get us 95% of the way.

**Comment by willingc** [comment]
You could also add an ``environment.yml`` to the root directory of this repo and then ask users to:

```
conda env create -f environment.yml
```

**Comment by jakevdp** [comment]
See https://github.com/conda-forge/staged-recipes/pull/1014

Once we release version 1.0, we can change the version & md5 there to match, and then create the recipe.

**Comment by ellisonbg** [comment]
Release is done (created a 1.0.0 tag)!!! Will post a note on the conda-forge PR
