### ISSUE TITLE
Test type inference

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#90]
When the `Layer.data` attribute is set, we trigger logic to infer the vegalite type of the channels based on what field (column) they are pointing to. Likewise, if `data` is set to `None`, the type inference should be reset. 

We need to write tests to make sure all of this is working.

**Comment by jakevdp** [comment]
One way we could fix this statefulness is to not have the type inference done until the JSON is generated. An advantage would be that for compound objects (Layer, Facet, etc.) type inference will work with data specified only once in the top-level wrapper. With the current approach, this is not the case.

The disadvantage would be that for interactive sessions, the feedback on a malformed encoding would be less immediate.

What do you think?

**Comment by ellisonbg** [comment]
Yeah, with the new higher level chart objects also taking data, I think the
statefulness will get pretty nasty. Also, right now we aren't really doing
anything before the JSON is generated that requires the type info. Also, if
we ever did need the type information, we could have a public API that
caused it to be generated upon request. Also, like this idea of simplifying
this part of the code - it is a bit subtle and prone to bugs.

On Mon, Jun 13, 2016 at 2:37 PM, Jake Vanderplas <notifications@github.com>
wrote:

> One way we could fix this statefulness is to not have the type inference
> done until the JSON is generated. An advantage would be that for compound
> objects (Layer, Facet, etc.) type inference will work with data specified
> only once in the top-level wrapper. With the current approach, this is not
> the case.
>
> The disadvantage would be that for interactive sessions, the feedback on a
> malformed encoding would be less immediate.
>
> What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/90#issuecomment-225716461>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0P_Zn1CfbDOyKiCDI3GOl3FHBKvKks5qLc2NgaJpZM4IZ2RS>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Good – I'll put some thought into how we might implement it that way.

**Comment by jakevdp** [comment]
I opened a PR in #134 which does this.

**Comment by jakevdp** [comment]
Done in #134
