### ISSUE TITLE
Make the defaults of our custom Enum types is None

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#91]
All of our default values should be None when we don't define anything. Right now, the default values for custom `Enum` types are empty strings rather than None. This is forcing is to add extra logic.

**Comment by jakevdp** [comment]
If I understand correctly, I think this is taken care of now in the generated code. For example the [AggregateOp](https://github.com/ellisonbg/altair/blob/master/altair/schema/_interface/aggregateop.py) is an enum, and where it is used in [SortField](https://github.com/ellisonbg/altair/blob/master/altair/schema/_interface/sortfield.py) it has a default value of None.

**Comment by ellisonbg** [comment]
Yes, I think so, closing.

On Mon, Jun 13, 2016 at 2:26 PM, Jake Vanderplas <notifications@github.com>
wrote:

> If I understand correctly, I think this is taken care of now in the
> generated code. For example the AggregateOp
> <https://github.com/ellisonbg/altair/blob/master/altair/schema/_interface/aggregateop.py>
> is an enum, and where it is used in SortField
> <https://github.com/ellisonbg/altair/blob/master/altair/schema/_interface/sortfield.py>
> it has a default value of None.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/91#issuecomment-225713909>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0JZ3RL4s_dvPypfP-WcetEKqOkyPks5qLcsjgaJpZM4IZ2TC>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
