### ISSUE TITLE
How to structure narrative docs for altair

### ISSUE THREAD

**Issue by ellisonbg** [ellisonbg/altair#94]
Vega-Lite itself now has very nice narrative docs. I am wondering how we want to handle the narrative docs for altair. Some options:

* Just add the equivalent altair/python code to the main Vega-Lite documentation and have that be the main single source of narrative documentation.
* Create notebooks for the examples that are in the Vega-Lite documentation to help with that.
* Keep it all completely separate.
* Offer tutorials on specific dataset in altair, similar to how seaborn has the nice one on the titanic dataset.

@domoritz

**Comment by domoritz** [comment]
I'm glad you like the VL docs (cc @kanitw). 

I'd keep the altair docs separate and like the idea of having a bunch of notebooks with tutorials. The set up docs and maybe some more structured API docs could be in the readme, the github wiki, or readthedocs.

**Comment by jakevdp** [comment]
I've begun working on some documentation-oriented notebooks. It's actually really helping me in understanding pain-points in the API.

**Comment by ellisonbg** [comment]
Awesome! I just pushed some small fixes related to accepting strings for
channels outside encode.

On Thu, May 19, 2016 at 11:28 AM, Jake Vanderplas <notifications@github.com>
wrote:

> I've begun working on some documentation-oriented notebooks. It's actually
> really helping me in understanding pain-points in the API.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/94#issuecomment-220411150>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
Yeah I agree we should start with documentation-oriented notebooks.  
This way we can revise the API syntax, independent of Vega-Lite project.  

Once we have a finalized syntax we might consider having tabs for vega-lite docs example, especially if we can write a function that automatically converts VL to Altair code.

**Comment by ellisonbg** [comment]
We have a good start on all of this in master. Closing...
