### ISSUE TITLE
population dataset not encodable as JSON

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#97]
Something is going on here... I'm having trouble figuring out what the problem is:

```python
>>> from altair import *
>>> population = load_dataset('population')
>>> Layer(population)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    907             method = _safe_get_formatter_method(obj, self.print_method)
    908             if method is not None:
--> 909                 method()
    910                 return True
    911 

/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/site-packages/vega-0.3.0-py3.5.egg/vega/base.py in _ipython_display_(self)
     47         )
     48         publish_display_data(
---> 49             {'application/javascript': self._generate_js(id)},
     50             metadata={'jupyter-vega': '#{0}'.format(id)}
     51         )

/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/site-packages/vega-0.3.0-py3.5.egg/vega/base.py in _generate_js(self, id)
     34         payload = template.format(
     35             selector=selector,
---> 36             spec=json.dumps(self.spec),
     37             type=self.render_type
     38         )

/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    228         cls is None and indent is None and separators is None and
    229         default is None and not sort_keys and not kw):
--> 230         return _default_encoder.encode(obj)
    231     if cls is None:
    232         cls = JSONEncoder

/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/encoder.py in default(self, o)
    178 
    179         """
--> 180         raise TypeError(repr(o) + " is not JSON serializable")
    181 
    182     def encode(self, o):

TypeError: 1850 is not JSON serializable
```

**Comment by ellisonbg** [comment]
That dataset has int64 dtype columns. Looks like those are numpy ints and
are not json serializable (they are not regular ints). This shows the issue:

```python
import numpy as np
json.dumps(np.int64(1))
```

I also just remembered that I haven't ported over the improved dataframe
sanitization function from ipyvega to altair. That would be the place to
put the logic.

On Thu, May 19, 2016 at 2:56 PM, Jake Vanderplas <notifications@github.com>
wrote:

> Something is going on here... I'm having trouble figuring out what the
> problem is:
>
> >>> from altair import *>>> population = load_dataset('population')>>> Layer(population)---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)/Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
>     907             method = _safe_get_formatter_method(obj, self.print_method)
>     908             if method is not None:--> 909                 method()
>     910                 return True
>     911
> /Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/site-packages/vega-0.3.0-py3.5.egg/vega/base.py in _ipython_display_(self)
>      47         )
>      48         publish_display_data(---> 49             {'application/javascript': self._generate_js(id)},
>      50             metadata={'jupyter-vega': '#{0}'.format(id)}
>      51         )
> /Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/site-packages/vega-0.3.0-py3.5.egg/vega/base.py in _generate_js(self, id)
>      34         payload = template.format(
>      35             selector=selector,---> 36             spec=json.dumps(self.spec),
>      37             type=self.render_type
>      38         )
> /Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
>     228         cls is None and indent is None and separators is None and
>     229         default is None and not sort_keys and not kw):--> 230         return _default_encoder.encode(obj)
>     231     if cls is None:
>     232         cls = JSONEncoder
> /Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/encoder.py in encode(self, o)
>     197         # exceptions aren't as detailed.  The list call should be roughly
>     198         # equivalent to the PySequence_Fast that ''.join() would do.--> 199         chunks = self.iterencode(o, _one_shot=True)
>     200         if not isinstance(chunks, (list, tuple)):
>     201             chunks = list(chunks)
> /Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/encoder.py in iterencode(self, o, _one_shot)
>     255                 self.key_separator, self.item_separator, self.sort_keys,
>     256                 self.skipkeys, _one_shot)--> 257         return _iterencode(o, 0)
>     258
>     259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,
>
> /Users/jakevdp/anaconda/envs/python3.5/lib/python3.5/json/encoder.py in default(self, o)
>     178
>     179         """
> --> 180         raise TypeError(repr(o) + " is not JSON serializable")
>     181
>     182     def encode(self, o):
> TypeError: 1850 is not JSON serializable
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/97>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
I just grepped the package, and it looks like the json encoding functionality is not actually used in altair, but is entirely in ipyvega. So it looks like the fix will have to be there.
We could probably remove the ``dataframe_to_json`` function from ``altair.utils``.

**Comment by ellisonbg** [comment]
Yes, and no. The part of it that we do in altair is convert the `DataFrame`
to a dict. Usually I have been trying to output a dict that can be JSON
serialized with no custom encoders (see `sanitize_dataframe` in ipyvega). I
think that altair can star to use that and we can improve that logic in
ipyega.

 And yes, we can remove the `dataframe_to_json` function.

On Thu, May 19, 2016 at 4:37 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I just grepped the package, and it looks like the json encoding
> functionality is not actually used in altair, but is entirely in ipyvega.
> So it looks like the fix will have to be there.
> We could probably remove the dataframe_to_json function from altair.utils.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/97#issuecomment-220478026>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Fixed via https://github.com/ellisonbg/altair/commit/5d9865ca4ab5406dc9a2d7ab28579b409d88afcf
