### ISSUE TITLE
[Discussion] Object API

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#98]
As I'm coding up the tutorial & examples, it strikes me that there's a confusing inconsistency in the API.

Consider this:
```python
from altair import *
data = load_dataset('cars')
Layer(data).encode(
    X('Horsepower', bin=Bin(maxbins=10)),
    y='count(*):Q'
).bar()
```
The ``encode()`` interface has some nice properties: that is, you can pass attributes either as an unnamed argument (e.g. ``X(...)``) or as a named argument (e.g. ``y=...``). The benefit here is that it makes the API intuitive and reduces duplication of information (vs. e.g. ``x=X(...)``).

When building these plots, I found it confusing that nested arguments don't allow the same flexibility. That is, I'd like to be able to write ``X('Horsepower', Bin(maxbins=10))`` or perhaps also ``X('Horsepower', bin={'maxbins':10})``. Could we override the ``__init__()`` method of traitlets to somehow do this sort of inference on input arguments?

cc/@ellisonbg

(Unrelated: the above snippet is how we spell "histogram" in Altair; we might think about a convenience method to wrap this).

**Comment by ellisonbg** [comment]
I think we should be able to get the `X('Horsepower', Bin(maxbins=10})` version working without much difficulty:

* We could set a `arg_name` attribute on the `Bin` class with a value of `bin` and then use that to convert positional args to kwargs. That would parallel what we do with the encoding stuff.
* This would require us to compiled a list of the Class<->arg_name that we could use when we are writing the auto-generated classes.
* It would require that each class in the spec is always used wit the same kwarg name, but I think it is.

Furthermore, we could give `Bin.maxbins` a default value that simplified it further to: `X('Horsepower', Bin())`

**Comment by jakevdp** [comment]
Great – would you like to start on that or should I?

Note that ``maxbins`` already has a default of 10 defined in the vegalite renderer.

**Comment by ellisonbg** [comment]
Go for it - I have to make a pass at email the rest of today :-(

On Thu, May 19, 2016 at 4:34 PM, Jake Vanderplas <notifications@github.com>
wrote:

> Great – would you like to start on that or should I?
>
> Note that maxbins already has a default of 10 defined in the vegalite
> renderer.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/98#issuecomment-220477324>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
@jakevdp did you already implement this in master?

**Comment by jakevdp** [comment]
Partially – I've implemented it in ``encode()`` and ``configure()``, I believe. What if we aim for this sort of thing in methods, but not in traitlet objects? I think we're getting pretty close to the point where there will be no need for users to directly touch traitlets which take a traitlet as an argument.

**Comment by ellisonbg** [comment]
I think that makes sense to implement it in the methods, but not the
traitlets objects.

On Mon, May 23, 2016 at 7:03 PM, Jake Vanderplas <notifications@github.com>
wrote:

> Partially – I've implemented it in encode() and configure(), I believe.
> What if we aim for this sort of thing in methods, but not in traitlet
> objects? I think we're getting pretty close to the point where there will
> be no need for users to directly touch traitlets which take a traitlet as
> an argument.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/98#issuecomment-221147214>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
@jakevdp do you think there is anything else to do on this one?

**Comment by jakevdp** [comment]
This idea is implemented within ``encode()``, and we could make that implementation a bit more general and use it within ``BaseObject`` as well. I think other things are a higher priority at the moment.

**Comment by jakevdp** [comment]
General version is now done in master.
